#!/usr/bin/env sh
set -ex

./build.sh

for EXCHANGE in "kraken" "binance" "coinbasepro"; do
  LOGLEVEL=DEBUG EXCHANGE="${EXCHANGE}" REFERENCE_CURRENCY="EUR" SYMBOLS="BTC/EUR" TEST=y ./crypto-exporter.sh
done

# Stellar
ADDRESSES='GA5XIGA5C7QTPTWXQHY6MCJRMTRZDOSHR6EFIBNDQTCQHG262N4GGKTM'  # kraken
ADDRESSES="${ADDRESSES},GD6RMKTCHQGEOGYWIKSY5G7QWXPZOAEZIKPKEVZUAXOQCZRVBRRFGLJM"  # NydroEnergy
ADDRESSES="${ADDRESSES},GCNSGHUCG5VMGLT5RIYYZSO7VQULQKAJ62QA33DBC5PPBSO57LFWVV6P"  # InterstellarExchange
EXCHANGE="stellar" ADDRESSES="${ADDRESSES}" TEST=y ./crypto-exporter.sh
